// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BoardTile
    {
        [DataMember(Name = "tile_id")]
        public uint TileId;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "owner_id")]
        public uint OwnerId;
        [DataMember(Name = "x")]
        public uint X;
        [DataMember(Name = "y")]
        public uint Y;
        [DataMember(Name = "has_ship")]
        public bool HasShip;
        [DataMember(Name = "hit")]
        public bool Hit;

        public BoardTile(
            uint TileId,
            uint GameId,
            uint OwnerId,
            uint X,
            uint Y,
            bool HasShip,
            bool Hit
        )
        {
            this.TileId = TileId;
            this.GameId = GameId;
            this.OwnerId = OwnerId;
            this.X = X;
            this.Y = Y;
            this.HasShip = HasShip;
            this.Hit = Hit;
        }

        public BoardTile()
        {
        }
    }
}
