// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Game
    {
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "player1_id")]
        public uint Player1Id;
        [DataMember(Name = "player2_id")]
        public uint Player2Id;
        [DataMember(Name = "current_turn_id")]
        public uint CurrentTurnId;
        [DataMember(Name = "game_started")]
        public bool GameStarted;
        [DataMember(Name = "game_ended")]
        public bool GameEnded;
        [DataMember(Name = "winner_id")]
        public uint WinnerId;

        public Game(
            uint GameId,
            uint Player1Id,
            uint Player2Id,
            uint CurrentTurnId,
            bool GameStarted,
            bool GameEnded,
            uint WinnerId
        )
        {
            this.GameId = GameId;
            this.Player1Id = Player1Id;
            this.Player2Id = Player2Id;
            this.CurrentTurnId = CurrentTurnId;
            this.GameStarted = GameStarted;
            this.GameEnded = GameEnded;
            this.WinnerId = WinnerId;
        }

        public Game()
        {
        }
    }
}
