// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ship
    {
        [DataMember(Name = "ship_id")]
        public uint ShipId;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "owner_id")]
        public uint OwnerId;
        [DataMember(Name = "length")]
        public uint Length;
        [DataMember(Name = "hit_count")]
        public uint HitCount;
        [DataMember(Name = "sunk")]
        public bool Sunk;

        public Ship(
            uint ShipId,
            uint GameId,
            uint OwnerId,
            uint Length,
            uint HitCount,
            bool Sunk
        )
        {
            this.ShipId = ShipId;
            this.GameId = GameId;
            this.OwnerId = OwnerId;
            this.Length = Length;
            this.HitCount = HitCount;
            this.Sunk = Sunk;
        }

        public Ship()
        {
        }
    }
}
