// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BoardTileHandle : RemoteTableHandle<EventContext, BoardTile>
        {
            protected override string RemoteTableName => "board_tile";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(BoardTile row) => row.GameId;

                public GameIdIndex(BoardTileHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class TileIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(BoardTile row) => row.TileId;

                public TileIdUniqueIndex(BoardTileHandle table) : base(table) { }
            }

            public readonly TileIdUniqueIndex TileId;

            internal BoardTileHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                TileId = new(this);
            }

            protected override object GetPrimaryKey(BoardTile row) => row.TileId;
        }

        public readonly BoardTileHandle BoardTile;
    }
}
