// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameHandle : RemoteTableHandle<EventContext, Game>
        {
            protected override string RemoteTableName => "game";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Game row) => row.GameId;

                public GameIdUniqueIndex(GameHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            internal GameHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
            }

            protected override object GetPrimaryKey(Game row) => row.GameId;
        }

        public readonly GameHandle Game;
    }
}
