// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShipHandle : RemoteTableHandle<EventContext, Ship>
        {
            protected override string RemoteTableName => "ship";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Ship row) => row.GameId;

                public GameIdIndex(ShipHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Ship row) => row.ShipId;

                public ShipIdUniqueIndex(ShipHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal ShipHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(Ship row) => row.ShipId;
        }

        public readonly ShipHandle Ship;
    }
}
