// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateGameHandler(ReducerEventContext ctx, uint opponentId);
        public event CreateGameHandler? OnCreateGame;

        public void CreateGame(uint opponentId)
        {
            conn.InternalCallReducer(new Reducer.CreateGame(opponentId), this.SetCallReducerFlags.CreateGameFlags);
        }

        public bool InvokeCreateGame(ReducerEventContext ctx, Reducer.CreateGame args)
        {
            if (OnCreateGame == null) return false;
            OnCreateGame(
                ctx,
                args.OpponentId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "opponent_id")]
            public uint OpponentId;

            public CreateGame(uint OpponentId)
            {
                this.OpponentId = OpponentId;
            }

            public CreateGame()
            {
            }

            string IReducerArgs.ReducerName => "CreateGame";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateGameFlags;
        public void CreateGame(CallReducerFlags flags) => CreateGameFlags = flags;
    }
}
