// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FireAtHandler(ReducerEventContext ctx, uint gameId, uint x, uint y);
        public event FireAtHandler? OnFireAt;

        public void FireAt(uint gameId, uint x, uint y)
        {
            conn.InternalCallReducer(new Reducer.FireAt(gameId, x, y), this.SetCallReducerFlags.FireAtFlags);
        }

        public bool InvokeFireAt(ReducerEventContext ctx, Reducer.FireAt args)
        {
            if (OnFireAt == null) return false;
            OnFireAt(
                ctx,
                args.GameId,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FireAt : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public uint GameId;
            [DataMember(Name = "x")]
            public uint X;
            [DataMember(Name = "y")]
            public uint Y;

            public FireAt(
                uint GameId,
                uint X,
                uint Y
            )
            {
                this.GameId = GameId;
                this.X = X;
                this.Y = Y;
            }

            public FireAt()
            {
            }

            string IReducerArgs.ReducerName => "FireAt";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags FireAtFlags;
        public void FireAt(CallReducerFlags flags) => FireAtFlags = flags;
    }
}
