// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceShipHandler(ReducerEventContext ctx, uint gameId, uint x, uint y, uint length, bool horizontal);
        public event PlaceShipHandler? OnPlaceShip;

        public void PlaceShip(uint gameId, uint x, uint y, uint length, bool horizontal)
        {
            conn.InternalCallReducer(new Reducer.PlaceShip(gameId, x, y, length, horizontal), this.SetCallReducerFlags.PlaceShipFlags);
        }

        public bool InvokePlaceShip(ReducerEventContext ctx, Reducer.PlaceShip args)
        {
            if (OnPlaceShip == null) return false;
            OnPlaceShip(
                ctx,
                args.GameId,
                args.X,
                args.Y,
                args.Length,
                args.Horizontal
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceShip : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public uint GameId;
            [DataMember(Name = "x")]
            public uint X;
            [DataMember(Name = "y")]
            public uint Y;
            [DataMember(Name = "length")]
            public uint Length;
            [DataMember(Name = "horizontal")]
            public bool Horizontal;

            public PlaceShip(
                uint GameId,
                uint X,
                uint Y,
                uint Length,
                bool Horizontal
            )
            {
                this.GameId = GameId;
                this.X = X;
                this.Y = Y;
                this.Length = Length;
                this.Horizontal = Horizontal;
            }

            public PlaceShip()
            {
            }

            string IReducerArgs.ReducerName => "PlaceShip";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlaceShipFlags;
        public void PlaceShip(CallReducerFlags flags) => PlaceShipFlags = flags;
    }
}
